apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: wa-cluster-1
        image: gcr.io/api-wa-400312/waapi:latest
        ports:
        - containerPort: 80
